### ISSUE TITLE
Downloaded zip version not working

### ISSUE THREAD

**Issue by Moganero** [hakimel/Ladda#103]
demo of Ladda works on [https://lab.hakim.se/ladda/](https://lab.hakim.se/ladda/) but the copy I downloaded (the zip file) but I'm having trouble getting it to work - I'm using the same browser in each case.

On the downloaded copy of the demo the spinner does not appear, the submit button takes me immediately to example.com.

I noticed that the css filenames mentioned in README.md do not match those in the css directory and 'dist' does not exist, so I created it and downloaded ladda.min.css, ladda.min.js and spin.min.js into it.  Looks like I'm not supposed to down load form-bundle.js though.

**Comment by theodorejb** [comment]
If you want to run the demo locally you have to follow the instructions in https://github.com/hakimel/Ladda/blob/master/CONTRIBUTING.md. To use Ladda in a project, install it from npm per the instructions in the readme.
