### ISSUE TITLE
Update 2.0.3 npm build failure

### ISSUE THREAD

**Issue by Donatello-za** [hakimel/Ladda#110]
I'm posting a new issue as I did not receive any feedback on the comment I made in this closed issue: https://github.com/hakimel/Ladda/issues/109

Is there a way to support both node.js and Dart Sass? When building our application we get the following error after the above change was made in v2.0.3:

```
Module build failed: ModuleBuildError: Module build failed: 
        right: math.div($spinnerSize, -2) + 10;
                  ^
      Invalid CSS after "...    right: math": expected expression (e.g. 1px, bold), was ".div($spinnerSize, "
      in <redacted>node_modules/ladda/css/ladda.scss (line 118, column 20)
```

**Comment by theodorejb** [comment]
Per https://github.com/sass/node-sass#readme:

> **Warning:** [LibSass and Node Sass are deprecated](https://sass-lang.com/blog/libsass-is-deprecated). While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto [Dart Sass](https://sass-lang.com/dart-sass).

So I recommend that you switch to Dart Sass in order to support modern Sass features and use the latest version of Ladda.

**Comment by Donatello-za** [comment]
Sure, we will eventually, I just think it isn't great to break backwards compatibility in a minor version update.

**Comment by theodorejb** [comment]
The change was necessary to avoid deprecation warnings when using Dart Sass (see #109). Since this was the only change in Ladda v2.0.3, feel free to continue using v2.0.2 until you are able to switch to Dart Sass.
