### ISSUE TITLE
style passed in during bind

### ISSUE THREAD

**Issue by Enalmada** [hakimel/Ladda#64]
Amazing library.  Silly question, can style be defined during bind?  I have a ton of buttons and I want them all styled the same way.  So I am trying to define style during bind and it doesn't seem to work, it seems to default still to expand-right.  

`
Ladda.bind('button.ladda-button', {timeout: 2000, style: "zoom-in"});
`

If style during bind doesn't work, then this is an enhancement request.

Thanks!

**Comment by theodorejb** [comment]
Have you considered creating your own function which adds a `data-style` attribute to the buttons and then calls `Ladda.bind`? I'd like to avoid having multiple APIs for doing the same thing.

**Comment by Enalmada** [comment]
No, but that seems like a very sensible workaround.   Since bind takes timeout, I figured it might be easy to let it take in more options but if there is a reason that passing in style as a default parameter to bind isn't a no brainer we can totally close this issue.

**Comment by stevebauman** [comment]
Dang was hoping the `options` param in the `Ladda.bind()` method would accept a default style parameter.
