### ISSUE TITLE
button.ladda( 'isLoading' ) returns button object instead of loading state

### ISSUE THREAD

**Issue by diesl** [hakimel/Ladda#65]
When using the jquery version of your script, `isLoading` returns the button object instead of a boolean loading state value. The normal javascript version works just fine.

Reproduce with:
```js
// Create a new instance of ladda for the specified button
var l = $( '.my-button' ).ladda();

// Check the current state
l.ladda( 'isLoading' );
```

**Comment by theodorejb** [comment]
The jQuery portion of this library is no longer being maintained, and the plan is to remove it in the next major version of Ladda. I recommend that you use the normal JavaScript API instead.

**Comment by diesl** [comment]
Thank you for the information!

>The jQuery portion of this library is no longer being maintained, and the plan is to remove it in the next major version of Ladda.

If it is not maintained, you should at least mention in the documentation that this particular method does not work, mark the jQuery part of the documentation as unmaintained or remove it completely so people will use the normal API right away.

**Comment by diesl** [comment]
Thanks for the fix 👍
