### ISSUE TITLE
Does not show any spinner

### ISSUE THREAD

**Issue by Jokero** [hakimel/Ladda#67]
Version - 1.0.4 from npm

html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="node_modules/ladda/dist/ladda.min.js"></script>
    <script src="node_modules/ladda/dist/spin.min.js"></script>
    <link rel="stylesheet" href="node_modules/ladda/dist/ladda-themeless.min.css">
</head>
<body>
<button class="ladda-button" data-style="expand-right"><span class="ladda-label">Submit</span></button>
</body>
</html>
```
All assets are loaded, I see button and it does not display any spinner on click:
![image](https://user-images.githubusercontent.com/434135/29979882-ef70ecfe-8f4f-11e7-9d1c-05f127ff8c4e.png)

What am I doing wrong?

**Comment by theodorejb** [comment]
First, you need to load the spin.js file before Ladda, as Ladda depends on it. Secondly, just loading JavaScript files won't add spinners to your buttons - you need to call `Ladda.bind()`, or call the `start()` method on an instance created with `Ladda.create()` per the instructions in the readme.
