### ISSUE TITLE
XSS vulnerability in third-party library

### ISSUE THREAD

**Issue by dwaxweiler** [hakimel/Ladda#69]
Be relying on spin.js, ladda is also not compliant with strict CSP (Content Security Policy). See: https://github.com/fgnass/spin.js/issues/115

**Comment by hth** [comment]
This is preventing me from even thinking about using this project.

**Comment by vlahanas** [comment]
Is it indeed a vulnerability? It seems that there is no intention of fixing this from spin.js collaborators, at least not in the near future.

**Comment by theodorejb** [comment]
I made a pull request for spin.js yesterday that fixes it, but none of the spin.js collaborators have commented on it yet: https://github.com/fgnass/spin.js/pull/343.

**Comment by theodorejb** [comment]
Fixed in v2.0.0-alpha.1: https://github.com/hakimel/Ladda/releases/tag/2.0.0-alpha.1
