### ISSUE TITLE
Release ladda@v2.0-alpha

### ISSUE THREAD

**Issue by terales** [hakimel/Ladda#78]
As @theodorejb wrote in #77:
> Spin.js 3.0 was rewritten as an ES6 module, so Ladda also has to be rewritten as an ES6 module to use it (which is a breaking change). The bulk of this work has already been completed in the 2.x branch (https://github.com/hakimel/Ladda/commits/2.x). However, I've been hesitant to publish a new version based on spin.js 3.0 since it can cause performance issues for certain usage scenarios (e.g. showing a spinner while other code is running). fgnass/spin.js#347 should fix this, but it doesn't work properly in Microsoft Edge, and **I'd like to wait until it does**.

Maybe we can release an alpha version with the bug indicated as unresolved?
For example, we could [use `next` tag](https://docs.npmjs.com/getting-started/using-tags#adding-tags) for npm.

**Comment by theodorejb** [comment]
v2.0.0-alpha.1 is now available: https://github.com/hakimel/Ladda/releases/tag/2.0.0-alpha.1
