### ISSUE TITLE
Modal blinking

### ISSUE THREAD

**Issue by FerreiraRaphael** [hakimel/Ladda#82]
So, I'm using https://github.com/sachinchoolur/ladda-angular on my project, for button directive with ladda, I'm opening this issue here, because this repo doesn't has a commit for some time.

My problem is that when I use Ladda in a button within a modal, the modal blinks in a strange way.
![peek 2018-03-06 18-43](https://user-images.githubusercontent.com/11987481/37060459-233c5e4a-216f-11e8-89ba-9339688b7269.gif)

And without Ladda it just don't blink.
![peek 2018-03-06 18-45](https://user-images.githubusercontent.com/11987481/37060502-44f20cba-216f-11e8-9c93-4dddef547153.gif)

So my question is, can I resolve this by updating Ladda in the ladda-angular project ?

**Comment by theodorejb** [comment]
If this is a bug in the ladda-angular package I would recommend filing an issue there. I've personally had success using https://github.com/remotty/angular-ladda for AngularJS projects, so you could also try using that instead.
