### ISSUE TITLE
bower install angular-ladda

### ISSUE THREAD

**Issue by kameelyan** [hakimel/Ladda#85]
Bower install angular-ladda is listing ladda as a dependency, but after downloading it it's not given the dist folder for ladda. Any ideas?

**Comment by kameelyan** [comment]
Looks like your .gitignore has /dist/ included.

**Comment by theodorejb** [comment]
Bower is no longer supported. Please install via npm or Yarn.

**Comment by kameelyan** [comment]
Might want to tell angular-ladda about that then because they're still using your bower install. What's the reason to not support such a common installer?

**Comment by theodorejb** [comment]
In that case I would recommend filing an issue with angular-ladda. It should still work as long as their dependency version is set to Ladda 1.x.

**Comment by theodorejb** [comment]
The reason for no longer supporting Bower is that it requires extra work to maintain, and no one is paying for this work. Even the [official Bower website](https://bower.io/) recommends migrating away from Bower to Yarn and Webpack.
