### ISSUE TITLE
 v2.0+ only support Typescript？

### ISSUE THREAD

**Issue by kinshines** [hakimel/Ladda#87]
I am wondering whether Ladda v2.0+ only support Typescript?
Or javascript and jquery are also supported?

**Comment by theodorejb** [comment]
You can still use Ladda with JavaScript as the example in the readme demonstrates. There's no longer a dedicated jQuery API, but the standard JS API should allow you to accomplish all the same things that could be done with the old jQuery API.

**Comment by Odravison** [comment]
@tiagomatosweb .

**Comment by tiagomatosweb** [comment]
Yeah, my app is really fresh which is Vuejs using Nuxt and I’ve faced the issue with Ladda 2.x. Even within unit test it does get error. So I gave up for the time being.

Hope it get fixed. Cheers
