### ISSUE TITLE
2.0.x releases don't have `dist` folder

### ISSUE THREAD

**Issue by IgorCode** [hakimel/Ladda#91]
Newer releases (from v2.0.0) don't have `dist` folder. Demo doesn't work because of this.

**Comment by theodorejb** [comment]
Releases installed from npm should always include the dist folder. It does appear that local dist folder generation was broken, though. This should be fixed now, and I added [contributing instructions](https://github.com/hakimel/Ladda/blob/master/CONTRIBUTING.md) for cloning the project and running the demo site locally.
