### ISSUE TITLE
Setting button to disabled in Start() prevents form submission in Chrome

### ISSUE THREAD

**Issue by dmednikov** [hakimel/Ladda#92]
FYI ...
If I have the following code in button click handler the button "disabled" property will be set to true. In that case Chrome will no longer submit the form.
```javascript
ButtonClickHandler(evt){
   this.$ladda = Ladda.create(evt.target);
   this.$ladda.start();
}
```
In my case re-enabling the button, and then putting code for disabling the button into the form.submit handler worked the best.

**Comment by theodorejb** [comment]
This doesn't look like a bug in Ladda. Rather than triggering Ladda via the button click event, you should do it via the form submit event.
