### ISSUE TITLE
v1.0.6: can't resolve spin.js

### ISSUE THREAD

**Issue by jamesarosen** [hakimel/Ladda#93]
[`ladda.min.js`](https://github.com/hakimel/Ladda/blob/1.0.6/dist/ladda.min.js) has
```js
require("spin.js")
```
but `dist/` includes `spin.min.js`, not `spin.js`. For use with Webpacker, this requires adding an alias:
```js
alias: {
  spin: resolve('node_modules/ladda/dist/spin.min.js'
}
```

**Comment by theodorejb** [comment]
Version 1.0.6 isn't supported anymore. In the latest release (2.0.1) the `dist/` folder only includes minified CSS files. Spin.js is a dependency of Ladda, and would have a path of `node_modules/spin.js/spin.js`.
